CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

ALTER TABLE briefs ADD COLUMN IF NOT EXISTS config JSONB DEFAULT '{}' NOT NULL;
ALTER TABLE briefs ADD COLUMN IF NOT EXISTS version INTEGER DEFAULT 1 NOT NULL;
ALTER TABLE briefs ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT true NOT NULL;
ALTER TABLE briefs ADD COLUMN IF NOT EXISTS parent_brief_id UUID;
